# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      chart: prometheus-node-exporter
      version: 4.45.2
  driftDetection:
    mode: enabled
  interval: 3m
  values:
    fullnameOverride: node-exporter
    hostNetwork: false
    prometheus:
      monitor:
        enabled: true
        jobLabel: app.kubernetes.io/instance
        relabelings:
          - targetLabel: kubernetes_node
            action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
          - targetLabel: nodename
            action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
          - targetLabel: instance
            action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - kubernetes_node
