apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s-garden-tls
  namespace: traefik
spec:
  # Secret names are always required.
  secretName: wildcard-k8s-garden-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Untersander
  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - k8s.garden
    - "*.k8s.garden"
  # ipAddresses:
    # - 192.168.0.5
  issuerRef:
    name: letsencrypt-dns01-prod
    kind: ClusterIssuer