apiVersion: v1
kind: ConfigMap
metadata:
  name: radvd-config
  namespace: dhcpv6-pd
data:
  radvd.conf: |
    # Default location /etc/radvd.conf
    interface br0 {

      # We are sending advertisements (route)
      AdvSendAdvert on;

      # When set, host use the administered (stateful) protocol
      # for address autoconfiguration. The use of this flag is
      # described in RFC 4862
      AdvManagedFlag on;

      # When set, host use the administered (stateful) protocol
      # for address autoconfiguration. For other (non-address)
      # information.
      # The use of this flag is described in RFC 4862
      AdvOtherConfigFlag on;

      # We have native Dual Stack IPv6 so we can use the regular MTU
      # https://blogs.cisco.com/enterprise/ipv6-mtu-gotchas-and-other-icmp-issues
      AdvLinkMTU 1500;

      prefix ::/64 {
        AdvOnLink on;
        AdvAutonomous on; ## SLAAC based on EUI
        AdvRouterAddr on;
      };
    };
