apiVersion: v1
kind: ConfigMap
metadata:
  name: radvd-config
  namespace: dhcpv6-pd
data:
  radvd.conf: |
    # Default location /etc/radvd.conf
    interface br0 {

      # We are sending advertisements (route)
      AdvSendAdvert on;

      # When set, host use the administered (stateful) protocol
      # for address autoconfiguration. The use of this flag is
      # described in RFC 4862
      AdvManagedFlag on;

      # When set, host use the administered (stateful) protocol
      # for address autoconfiguration. For other (non-address)
      # information.
      # The use of this flag is described in RFC 4862
      AdvOtherConfigFlag on;

      # We have native Dual Stack IPv6 so we can use the regular MTU
      # https://blogs.cisco.com/enterprise/ipv6-mtu-gotchas-and-other-icmp-issues
      AdvLinkMTU 1500;

      prefix ::/64 {
        AdvOnLink on;
        AdvAutonomous on; ## SLAAC based on EUI
        AdvRouterAddr on;
      };
    };


    ########### OPEN-RC init script ##############
    # TODO use as base to run my own
    # #!/sbin/openrc-run
    # # Copyright 1999-2011 Gentoo Foundation
    # # Distributed under the terms of the GNU General Public License v2
    # # $Header: /var/cvsroot/gentoo-x86/net-misc/radvd/files/radvd.init,v 1.6 2011/12/04 10:14:13 swegener Exp $

    # CONFIGFILE=/etc/radvd.conf
    # PIDFILE=/run/radvd/radvd.pid
    # SYSCTL_FORWARD=net.ipv6.conf.all.forwarding

    # extra_started_commands="reload"

    # depend() {
    # 	need net
    # 	after firewall
    # }

    # checkconfig() {
    # 	if [ ! -f "${CONFIGFILE}" ]; then
    # 		eerror "Configuration file ${CONFIGFILE} not found"
    # 		return 1
    # 	fi

    # 	checkpath -d -o radvd:radvd ${PIDFILE%/*}
    # }

    # start() {
    # 	checkconfig || return 1

    # 	ebegin "Starting IPv6 Router Advertisement Daemon"
    # 	start-stop-daemon --start --exec /usr/sbin/radvd \
    # 		--pidfile "${PIDFILE}" \
    # 		-- -C "${CONFIGFILE}" -p "${PIDFILE}" -u radvd ${OPTIONS}
    # 	eend $?
    # }

    # stop() {
    # 	ebegin "Stopping IPv6 Router Advertisement Daemon"
    # 	start-stop-daemon --stop --exec /usr/sbin/radvd --pidfile "${PIDFILE}"
    # 	eend $?
    # }

    # reload() {
    # 	checkconfig || return 1

    # 	ebegin "Reloading IPv6 Router Advertisement Daemon"
    # 	start-stop-daemon --stop --signal HUP --oknodo \
    # 		--exec /usr/sbin/radvd --pidfile "${PIDFILE}"
    # 	eend $?
    # }