# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      chart: metrics-server
      version: 3.13.0
  driftDetection:
    mode: enabled
  interval: 3m