# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
      chart: jellyfin
      version: 2.7.0
  driftDetection:
    mode: enabled
  interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-values # Default name, changed using Kustomization
