# Jellyfin gets the media folder (movies/, series/, home/); paperless lives in /var/mnt/zpool/paperless
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/mnt/zpool/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cp-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: "local-storage"
  volumeName: jellyfin-media
