# NVIDIA RuntimeClass https://www.talos.dev/v1.6/talos-guides/configuration/nvidia-gpu/#deploying-nvidia-device-plugin
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia