apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-credentials
  namespace: backup
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .accessKeyID}}
          aws_secret_access_key={{ .secretAccessKey}}
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: /Garage S3 backup-key/access key id
    - secretKey: secretAccessKey
      remoteRef:
        key: /Garage S3 backup-key/secret access key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze-credentials
  namespace: backup
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .accessKeyID}}
          aws_secret_access_key={{ .apiKey}}
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: /Backblaze B2 backup-k8s-garden/keyID
    - secretKey: apiKey
      remoteRef:
        key: /Backblaze B2 backup-k8s-garden/credential
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
  namespace: backup
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    template:
      data:
        repository-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "/Velero S3 repo encrypt password/credential"
