apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    - secretKey: external-dns-cloudflare-api-key
      remoteRef:
        key: "Cloudflare Edit all Zones Token/credential"
