# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/garage.rajsingh.info/garagereferencegrant_v1beta1.json
# Allow GarageKeys in the backup-test namespace to use the test buckets
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: backup-test
spec:
  from:
    - kind: GarageKey
      namespace: backup-test
  to:
    - kind: GarageBucket
      name: kopiur-test
    - kind: GarageBucket
      name: k8up-test
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/garage.rajsingh.info/garagereferencegrant_v1beta1.json
# Allow GarageKeys in the pihole namespace to use the app backup buckets
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: pihole
spec:
  from:
    - kind: GarageKey
      namespace: pihole
  to:
    - kind: GarageBucket
      name: kopiur-apps
    - kind: GarageBucket
      name: k8up-apps
