apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
  namespace: observability
spec:
  selector:
    matchLabels:
      app: speedtest-exporter
  namespaceSelector:
    matchNames:
    - observability
  endpoints:
  - port: metrics
    interval: 60m
    scrapeTimeout: 60s
    path: /metrics
