# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: flux-system
      chart: kubelet-csr-approver
      version: 1.2.11
  driftDetection:
    mode: enabled
  interval: 3m
  values:
    providerRegex: '^cp-.*'
    providerIpPrefixes: '10.0.0.0/24'
    bypassDnsResolution: 'true'
