# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
# Having Cilium values in a separate `values.yaml` is more comfortable.
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./values.yaml
configurations:
  - nameReference.yaml
