# yaml-language-server: $schema=https://json.schemastore.org/kustomization
# kopiur backups of PVCs labeled backup.k8s.garden/app=${APP} and the populator Restore ${APP}, see ../README.md
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./kopiur.yaml
  - ./restore.yaml
