# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      chart: cert-manager
      version: 1.18.2
  driftDetection:
    mode: enabled
  interval: 3m
  values:
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
    crds:
      enabled: true
    prometheus:
      enabled: true
