---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: Kubernetes
      auth:
        serviceAccountSecretRef:
          name: onepasswordsecret
          namespace: external-secrets
          key: token
  # Limit the scope of this ClusterSecretStore to the namespaces where it can be used.
  conditions:
    - namespaceRegexes:
        - ".*"
