---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
spec:
  refreshInterval: 1800
  retrySettings:
    maxRetries: 24
    retryInterval: 1h0m0s
  provider:
    onepasswordSDK:
      vault: Kubernetes
      cache:
        ttl: 2h0m0s
      auth:
        serviceAccountSecretRef:
          name: onepasswordsecret
          namespace: external-secrets
          key: token
  # Limit the scope of this ClusterSecretStore to the namespaces where it can be used.
  conditions:
    - namespaceRegexes:
        - ".*"
