# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      chart: openebs
      version: 4.4.0
  driftDetection:
    mode: enabled
  interval: 3m
  values:
    localpv-provisioner:
      hostpathClass:
        enabled: false
    zfs-localpv:
      zfsNode:
        encrKeysDir: /var/mnt/local-system-ssd/openebs/keys
    engines:
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
