machine:
  kernel:
    modules:
      - name: zfs
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 50GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-system-ssd
provisioning:
  diskSelector:
    match: system_disk
  minSize: 50GiB
  grow: true