apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: k8sgarden
  annotations:
    external-dns: public
spec:
  endpoints:
  - dnsName: k8s.garden
    recordType: AAAA
    targets:
    - "2a02:169:4a00::"
  - dnsName: "*.k8s.garden"
    recordType: A
    targets:
    - 10.0.0.20
  - dnsName: vpn.k8s.garden
    recordType: AAAA
    targets:
    - 2a02:169:4a00::1