apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: noreplay-org
  annotations:
    external-dns: public
spec:
  endpoints:
  - dnsName: "*.noreplay.org"
    recordType: A
    targets:
    - 10.0.0.20
