apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vpnk8sgarden
  annotations:
    external-dns: public
spec:
  endpoints:
  - dnsName: vpn.k8s.garden
    recordType: A
    targets:
    - 109.202.197.194