apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "openebs-zfs-retain"