apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-infra-admin-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    template:
      data:
        admin-token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: /Garage Infra Admin Token/credential
