# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/garage.rajsingh.info/garagereferencegrant_v1beta1.json
# Allow backup buckets/keys and namespaces that opted into backups to use this cluster
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: backup
spec:
  from:
    - kind: GarageBucket
      namespace: backup
    - kind: GarageKey
      namespace: backup
    - kind: GarageKey
      namespaceSelector:
        matchLabels:
          backup.k8s.garden/enabled: "true"
    # TODO: remove once pihole uses the backup components
    - kind: GarageKey
      namespace: pihole
  to:
    - kind: GarageCluster
      name: garage-infra
