apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: pihole
  labels:
    backup.k8s.garden/app: pihole
    backup.k8s.garden/copy-method: Direct # openebs-hostpath-ssd sc (cluster default) has no CSI snapshots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
