apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-webserver-api-secret
  namespace: pihole
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  target:
    template:
      data:
        FTLCONF_webserver_api_password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /pihole/password