# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./l2.yaml
  - ./ciliumnetworkpolicy.yaml
configMapGenerator:
  - name: paperless-samba-config
    files:
      - smb.conf=./smb.conf
generatorOptions:
  disableNameSuffixHash: true
