apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1

  storage:
    size: 5Gi
    storageClass: openebs-hostpath-ssd-retain
  # To restore from old pv, use the following configuration:
    # pvcTemplate:
    #   accessModes:
    #     - ReadWriteOnce
    #   resources:
    #     requests:
    #       storage: 5Gi
    #   volumeMode: Filesystem
    #   volumeName: pvc-84660cf2-b0c1-4c66-8f00-9bbec45c8158
    #   storageClassName: openebs-hostpath-ssd-retain

  # Switch permissions of immich to superuser to be able to restore with immich, or restore another way
  # enableSuperuserAccess: true

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.2-1.1.0
  primaryUpdateMethod: switchover
  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;